# Generated by Django 2.0.5 on 2018-06-12 22:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(help_text='Formato: V012345678', max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='Formato de cédula inválido , ej: V0123456', regex='^[V|E]{1}[0]{1}[0-9]{7,9}$')])),
                ('nombrepa', models.CharField(blank=True, max_length=30)),
                ('apellidopa', models.CharField(blank=True, max_length=30)),
                ('apellidoma', models.CharField(blank=True, max_length=30)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('fecha_nac', models.DateField()),
                ('telefono', models.PositiveIntegerField(blank=True, null=True)),
                ('domicilio', models.TextField()),
            ],
        ),
    ]
