# Generated by Django 2.0.5 on 2018-06-13 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paciente', '0002_paciente_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='fecha_nac',
            field=models.DateField(help_text='Formato: 2018-01-01'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefono',
            field=models.PositiveIntegerField(),
        ),
    ]
