# Generated by Django 2.0.5 on 2018-06-26 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paciente', '0003_auto_20180626_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='telefono',
            field=models.CharField(max_length=11),
        ),
    ]
