# Generated by Django 2.0.5 on 2018-05-29 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Paciente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellidoma', models.CharField(max_length=50)),
                ('apellidopa', models.CharField(max_length=50)),
                ('sexo', models.CharField(max_length=10)),
                ('fecha_nac', models.DateField()),
                ('edad', models.IntegerField()),
                ('email', models.TextField()),
                ('telefono', models.CharField(max_length=12)),
                ('domicilio', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Bioanalista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellidoma', models.CharField(max_length=50)),
                ('apellidopa', models.CharField(max_length=50)),
                ('sexo', models.CharField(max_length=10)),
                ('fecha_nac', models.DateField()),
                ('edad', models.IntegerField()),
                ('email', models.TextField()),
                ('telefono', models.CharField(max_length=12)),
                ('domicilio', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Muestra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modalidad', models.CharField(max_length=50)),
                ('monto', models.IntegerField()),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Paciente.Paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('examen', models.ManyToManyField(to='Laboratorio.Examen')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('fecha_sol', models.DateField()),
                ('asistente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Laboratorio.Asistente')),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Paciente.Paciente')),
            ],
        ),
    ]
