# Generated by Django 2.0.5 on 2018-06-15 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('examenes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellidoma', models.CharField(max_length=50)),
                ('apellidopa', models.CharField(max_length=50)),
                ('sexo', models.CharField(max_length=10)),
                ('fecha_nac', models.DateField()),
                ('edad', models.IntegerField()),
                ('email', models.TextField()),
                ('telefono', models.CharField(max_length=12)),
                ('domicilio', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Bioanalista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellidoma', models.CharField(max_length=50)),
                ('apellidopa', models.CharField(max_length=50)),
                ('sexo', models.CharField(max_length=10)),
                ('fecha_nac', models.DateField()),
                ('edad', models.IntegerField()),
                ('email', models.TextField()),
                ('telefono', models.CharField(max_length=12)),
                ('domicilio', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_examen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valores', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modalidad', models.CharField(max_length=50)),
                ('monto', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valores', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_sol', models.DateField(help_text='Formato: 2018-01-01')),
                ('asistente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Laboratorio.Asistente')),
                ('examenes', models.ManyToManyField(to='examenes.Examenes')),
            ],
        ),
    ]
