# Generated by Django 2.0.5 on 2018-06-05 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examenes', '0001_initial'),
        ('Laboratorio', '0002_auto_20180605_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultado',
            name='examenes',
            field=models.ManyToManyField(to='examenes.Examenes'),
        ),
    ]
