# Generated by Django 2.0.5 on 2018-06-13 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Laboratorio', '0002_auto_20180612_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='fecha_sol',
            field=models.DateField(help_text='Formato: 2018-01-01'),
        ),
    ]
