# Generated by Django 2.0.5 on 2018-06-24 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Paciente', '0002_paciente_user'),
        ('examenes', '0001_initial'),
        ('Laboratorio', '0003_auto_20180615_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleExamen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valores', models.CharField(max_length=9)),
                ('examen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='examenes.Examenes')),
                ('list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resultado', to='Laboratorio.Resultado')),
            ],
        ),
        migrations.CreateModel(
            name='TodoItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Buy milk, wash dog etc', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='detalle_examen',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Paciente.Paciente'),
        ),
        migrations.AlterField(
            model_name='detalle_examen',
            name='valores',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='todoitem',
            name='list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Laboratorio.TodoList'),
        ),
    ]
