# Generated by Django 2.0.5 on 2018-06-25 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Paciente', '0002_paciente_user'),
        ('Laboratorio', '0004_auto_20180624_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadoDat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Paciente.Paciente')),
            ],
        ),
        migrations.AddField(
            model_name='detalle_examen',
            name='resultadodat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Laboratorio.ResultadoDat'),
        ),
    ]
