# Generated by Django 2.0.5 on 2018-06-05 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Laboratorio', '0004_auto_20180605_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultado',
            name='solicitud',
        ),
        migrations.RemoveField(
            model_name='resultado',
            name='examenes',
        ),
        migrations.AddField(
            model_name='resultado',
            name='examenes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Laboratorio.Asistente'),
        ),
    ]
