# Generated by Django 2.0.5 on 2018-06-05 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Laboratorio', '0005_auto_20180605_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultado',
            name='examenes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='examenes.Examenes'),
        ),
    ]
