# Generated by Django 2.0.5 on 2018-06-25 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Laboratorio', '0005_auto_20180625_0205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalle_examen',
            name='paciente',
        ),
    ]
