# Generated by Django 2.0.5 on 2018-06-05 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Paciente', '0001_initial'),
        ('Laboratorio', '0006_auto_20180605_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultado',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Paciente.Paciente'),
        ),
    ]
