# Generated by Django 2.0.5 on 2018-06-25 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Laboratorio', '0006_remove_detalle_examen_paciente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='list',
        ),
        migrations.DeleteModel(
            name='TodoItem',
        ),
        migrations.DeleteModel(
            name='TodoList',
        ),
    ]
