# Generated by Django 2.0.5 on 2018-06-25 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Laboratorio', '0007_auto_20180625_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle_examen',
            name='fecharesultado',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
