# Generated by Django 2.0.5 on 2018-06-25 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Laboratorio', '0008_detalle_examen_fecharesultado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleexamen',
            name='examen',
        ),
        migrations.RemoveField(
            model_name='detalleexamen',
            name='list',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='paciente',
        ),
        migrations.RemoveField(
            model_name='resultado',
            name='examen',
        ),
        migrations.RemoveField(
            model_name='resultado',
            name='examenes',
        ),
        migrations.RemoveField(
            model_name='resultado',
            name='paciente',
        ),
        migrations.DeleteModel(
            name='DetalleExamen',
        ),
        migrations.DeleteModel(
            name='Pago',
        ),
        migrations.DeleteModel(
            name='Resultado',
        ),
    ]
