# Generated by Django 2.0.5 on 2018-06-26 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Laboratorio', '0011_resultadodat_solicitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle_examen',
            name='validacion',
            field=models.BooleanField(default=False),
        ),
    ]
