# Generated by Django 2.0.5 on 2018-06-15 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Examenes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('tipo', models.CharField(choices=[('hematologia', 'Hematologia'), ('orina', 'Orina')], max_length=30)),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('precio_laboratorio', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
            ],
        ),
    ]
