# Generated by Django 2.0.5 on 2018-06-25 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examenes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examenes',
            name='rango',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
