# Generated by Django 2.0.5 on 2018-06-25 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examenes', '0002_examenes_rango'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examenes',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='examenes',
            name='precio_laboratorio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
